// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb0Cugj4tv0LqwDd9brr2f0bKRYtt2yjw',
    appId: '1:396001474859:web:20d4c5c81b3635c05ead6e',
    messagingSenderId: '396001474859',
    projectId: 'mychatapp-728c7',
    authDomain: 'mychatapp-728c7.firebaseapp.com',
    storageBucket: 'mychatapp-728c7.appspot.com',
    measurementId: 'G-2GSC28SB3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9HAE92GqJcmtDtgBRUPCjMRJj0691W08',
    appId: '1:396001474859:android:36079d31857031b85ead6e',
    messagingSenderId: '396001474859',
    projectId: 'mychatapp-728c7',
    storageBucket: 'mychatapp-728c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-PM7SmhRbXIq0sEhaap-Q7ZPLNO5UdEs',
    appId: '1:396001474859:ios:e35025d1fa6b62275ead6e',
    messagingSenderId: '396001474859',
    projectId: 'mychatapp-728c7',
    storageBucket: 'mychatapp-728c7.appspot.com',
    iosBundleId: 'com.example.myChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-PM7SmhRbXIq0sEhaap-Q7ZPLNO5UdEs',
    appId: '1:396001474859:ios:e35025d1fa6b62275ead6e',
    messagingSenderId: '396001474859',
    projectId: 'mychatapp-728c7',
    storageBucket: 'mychatapp-728c7.appspot.com',
    iosBundleId: 'com.example.myChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb0Cugj4tv0LqwDd9brr2f0bKRYtt2yjw',
    appId: '1:396001474859:web:2d7408f7114674945ead6e',
    messagingSenderId: '396001474859',
    projectId: 'mychatapp-728c7',
    authDomain: 'mychatapp-728c7.firebaseapp.com',
    storageBucket: 'mychatapp-728c7.appspot.com',
    measurementId: 'G-MTWMBV7D4N',
  );
}
